---
- name: "Run pre-checks"
  ansible.builtin.include_tasks: precheck.yml
  tags:
    - precheck

- name: "Installs Keycloak"
  ansible.builtin.include_tasks: install.yml
  tags:
    - install

- name: "Configure Keycloak"
  ansible.builtin.include_tasks: configure.yml
  tags:
    - setup
