---
- name: "Copy SSL Certificate and Key (systemd < 247)"
  become: true
  become_user: root
  when: ansible_systemd_version | int < 247
  notify: "Restart Keycloak"
  ansible.builtin.copy:
    remote_src: true
    src: "{{ item.0 }}"
    dest: "{{ item.1 }}"
    mode: "{{ item.2 }}"
    owner: "{{ keycloak_service_user }}"
    group: "{{ keycloak_service_user }}"
  loop: "{{ files }}"
  vars:
    files:
      - ["{{ keycloak_cert_file }}", "{{ keycloak_config_folder }}/server.crt", '0660']
      - ["{{ keycloak_key_file }}", "{{ keycloak_config_folder }}/server.key", '0600']

- name: "Setup Certificate & Key for HTTPS (systemd < 247)"
  when: ansible_systemd_version | int < 247
  notify: "Restart Keycloak"
  ansible.builtin.lineinfile:
    path: "{{ keycloak_config_folder }}/keycloak.conf"
    state: present
    owner: "{{ keycloak_service_user }}"
    group: "{{ keycloak_service_user }}"
    mode: '0660'
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
    regexp: "{{ item.regexp }}"
  loop: "{{ cert_params }}"
  vars:
    cert_params:
      - line: "https-certificate-file=${kc.home.dir}conf/server.crt"
        insertafter: '#https-certificate-file=${kc.home.dir}conf/server.crt.pem'
        regexp: '^https-certificate-file=.*'
      - line: "https-certificate-key-file=${kc.home.dir}conf/server.key"
        insertafter: '#https-certificate-key-file=${kc.home.dir}conf/server.key.pem'
        regexp: '^https-certificate-key-file=.*'
