---
- name: "Check presence of keystore"
  ansible.builtin.stat:
    path: "{{ keycloak_keystore_file }}"
  register: keystore_file

- name: "Setup TLS with certificate in keystore"
  when: keystore_file.stat.exists
  block:
    - name: "Ensure correct permissions on keystore"
      become: true
      become_user: root
      ansible.builtin.file:
        path: "{{ keycloak_keystore_file }}"
        owner: "{{ keycloak_service_user }}"
        group: "{{ keycloak_service_user }}"
        mode: '0660'

    - name: "Add keystore-related parameters in Keycloak config"
      ansible.builtin.blockinfile:
        path: "{{ keycloak_config_folder }}/keycloak.conf"
        state: present
        owner: "{{ keycloak_service_user }}"
        group: "{{ keycloak_service_user }}"
        mode: '0660'
        marker: "### {mark} TLS ANSIBLE MANAGED BLOCK ###"
        block: |
          # HTTPS / TLS keystore
          https-key-store-file={{ keycloak_keystore_file }}
          https-key-store-password={{ keycloak_keystore_password }}
