---
- name: Define enabled features
  when: keycloak_enabled_features | length > 0
  community.general.ini_file:  # noqa: args[module] risky-file-permissions
    option: features
    value: "{{ keycloak_enabled_features | join(',') }}"

- name: Define disabled features
  when: keycloak_disabled_features | length > 0
  community.general.ini_file:  # noqa: args[module] risky-file-permissions
    option: features-disabled
    value: "{{ keycloak_disabled_features | join(',') }}"
