---
- name: "Check proxy-headers value"
  ansible.builtin.assert:
    that:
      - keycloak_proxy_headers in ['forwarded', 'xforwarded']
    fail_msg: "'keycloak_proxy_headers' should be either 'forwarded' or 'xforwarded'"

- name: "Set default variables for keycloak config"
  ansible.builtin.set_fact:
    default_config_vars:
      - option: hostname
        value: "{{ keycloak_protocol }}://{{ keycloak_hostname }}"
      - option: hostname-admin
        value: "{{ keycloak_protocol }}://{{ keycloak_admin_hostname | default(keycloak_hostname) }}"
      - option: proxy-headers
        value: "{{ keycloak_proxy_headers }}"
      - option: http-enabled
        value: "{{ keycloak_http_enabled }}"
      - option: health-enabled
        value: "{{ keycloak_health_enabled | default(False) }}"

- name: "Define network config options in conf file"
  community.general.ini_file:  # noqa: args[module] risky-file-permissions
    option: "{{ option }}"
    value: "{{ value }}"
    vars:
      option: "{{ item.key | default(item.option) }}"
      value: "{{ item.value | ternary('true', 'false') if item.value == item.value|bool else item.value }}"
    loop: "{{ default_config_vars | default({}, true) | dict2items }}"
