---
- name: "Setup Keycloak network parameters"
  notify: "Restart Keycloak"
  block:
    - name: "Defaults admin hostname to Keycloak frontend hostname"
      when: keycloak_admin_hostname is not defined
      ansible.builtin.set_fact:
        keycloak_admin_hostname: "{{ keycloak_hostname }}"

    - name: "Define hostnames"
      ansible.builtin.blockinfile:
        path: "{{ keycloak_config_folder }}/keycloak.conf"
        state: present
        owner: "{{ keycloak_service_user }}"
        group: "{{ keycloak_service_user }}"
        mode: '0660'
        marker: '### {mark} HOST ANSIBLE MANAGED BLOCK ###'
        block: |
          hostname={{ keycloak_hostname }}
          hostname-admin={{ keycloak_admin_hostname }}
        insertafter: '#hostname=myhostname'

    - name: "Set proxy mode"
      when: keycloak_proxy_mode is defined
      ansible.builtin.blockinfile:
        path: "{{ keycloak_config_folder }}/keycloak.conf"
        state: present
        owner: "{{ keycloak_service_user }}"
        group: "{{ keycloak_service_user }}"
        mode: '0660'
        marker: '### {mark} PROXY ANSIBLE MANAGED BLOCK ###'
        block: |
          proxy={{ keycloak_proxy_mode }}
          hostname-strict=false
          hostname-strict-backchannel=false
        insertafter: '#proxy=reencrypt'

    - name: "Unset proxy mode if not defined"
      when: keycloak_proxy_mode is not defined
      ansible.builtin.lineinfile:
        path: "{{ keycloak_config_folder }}/keycloak.conf"
        state: absent
        owner: "{{ keycloak_service_user }}"
        group: "{{ keycloak_service_user }}"
        mode: '0660'
        regexp: '^proxy=.*'

    - name: "Enable Health endpoint"
      when: keycloak_health_enabled is defined and keycloak_health_enabled
      ansible.builtin.lineinfile:
        path: "{{ keycloak_config_folder }}/keycloak.conf"
        state: present
        owner: "{{ keycloak_service_user }}"
        group: "{{ keycloak_service_user }}"
        mode: '0660'
        regexp: '^health-enabled=.*'
        line: "health-enabled=true"
        insertafter: '#health-enabled=true'

    - name: "Disable health endpoint"
      when: keycloak_health_enabled is not defined or not keycloak_health_enabled
      ansible.builtin.lineinfile:
        path: "{{ keycloak_config_folder }}/keycloak.conf"
        state: absent
        owner: "{{ keycloak_service_user }}"
        group: "{{ keycloak_service_user }}"
        mode: '0660'
        regexp: '^health-enabled=.*'
